# Generated by Django 5.0.7 on 2024-07-24 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('soju_goal', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('beer_goal', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('mak_goal', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('wine_goal', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('cheer', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
