# Generated by Django 5.0.7 on 2024-07-30 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('a1', models.BooleanField(null=True)),
                ('a2', models.BooleanField(null=True)),
                ('a3', models.BooleanField(null=True)),
                ('a4', models.BooleanField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('level', models.IntegerField(null=True)),
                ('q1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q1', to='testsystem.testquestion')),
                ('q2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q2', to='testsystem.testquestion')),
                ('q3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q3', to='testsystem.testquestion')),
                ('q4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q4', to='testsystem.testquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
