# Generated by Django 3.2.25 on 2024-07-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='stage',
            field=models.IntegerField(default=1),
        ),
    ]
