# Generated by Django 3.2.25 on 2024-07-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mypage_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypage',
            name='nickname',
            field=models.CharField(blank=True, default='익명', max_length=20),
        ),
    ]
