# Generated by Django 5.0.7 on 2024-07-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
