# Generated by Django 5.0.7 on 2024-07-26 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='count',
        ),
    ]
