# Generated by Django 5.0.7 on 2024-08-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_record_beer_record_alter_record_mak_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='beer_record',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='mak_record',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='soju_record',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='wine_record',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
